### ISSUE TITLE
The plugin is incompatible with symfony 6.0 (and Sylius 1.12)

### ISSUE THREAD

**Issue by jarekmajcher** [spinbits/sylius-google-analytics-plugin#26]
If I install plugin on Sylius 1.12 I get error:

`Compile Error: Declaration of Spinbits\SyliusGoogleAnalytics4Plugin\DependencyInjection\SpinbitsSyliusGoogleAnalytics4Extension::getAlias() must be compatible with Symfony\Component\DependencyInjection\Extension\Extension::getAlias(): string`

Since Symfony 6.0 function getAlias() must have a return type declaration (string).

Could you confirm this error?

**Comment by jakublech** [comment]
Thanks for report. I'll do my best to fix it until end of the week.
